config/routes.rb
Spree::Core::Engine.routes.prepend do
  namespace :admin do
    resources :banners do
      collection do
        post :update_positions
      end
      resources :taxons do
        member do
          get :select_taxon
          delete :remove_taxon
        end
        collection do
          post :available_taxons
          get  :selected_taxon
        end
      end
    end
  end
end

app/models/spree/banner.rb
module Spree
  class Banner < ActiveRecord::Base

    POSITIONS = {:top => 1, :right => 2, :bottom => 3, :left => 4}

    validates_presence_of :title, :attachment_width, :attachment_height
    validates_attachment_presence :attachment
    validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'image/gif'], :message => "must be JPG, JPEG or PNG"

    has_and_belongs_to_many :taxons, :join_table => 'spree_banners_taxons'

    attr_accessible :title, :url, :position, :attachment_width, :attachment_height, :enabled, :attachment

    has_attached_file :attachment,
      :url  => "/spree/banners/:id/:style_:basename.:extension",
      :path => ":rails_root/public/spree/banners/:id/:style_:basename.:extension",
      :styles => {
      :thumbnail => "80x80#",
      :custom => Proc.new { |instance| "#{instance.attachment_width}x#{instance.attachment_height}#" }
    },
      :convert_options => {
      :thumbnail => "-gravity center"
    }
    after_post_process :find_dimensions

    scope :enabled, where(:enabled => true)
    scope :by_position, lambda {|position| where(:enabled => true, :position => position) }

    def initialize(*args)
      super(*args)
      last_banner = Banner.last
      self.position = last_banner ? last_banner.position + 1 : 0
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end
  end
end

app/controllers/spree/admin/banners_controller.rb
module Spree
  module Admin
    class Admin::BannersController < ResourceController
      before_filter :load_data

      def model_class
        Banner
      end

      def update_positions
        params[:positions].each do |id, index|
          Spree::Banner.update_all(['position=?', index], ['id=?', id])
        end

        respond_to do |format|
          format.html { redirect_to admin_banners_url() }
          format.js  { render :text => 'Ok' }
        end
      end

      def load_data
        @banners = Spree::Banner.all
      end

      private

      def location_after_save
        admin_banners_url(@banner)
      end

    end
  end
end

app/controllers/spree/admin/taxons_controller_decorator.rb
Spree::Admin::TaxonsController.class_eval do
  def available_taxons
    @banner = Spree::Banner.find(params[:banner_id])
    @taxons = params[:q].blank? ? [] : Spree::Taxon.where('lower(name) LIKE ?', "%#{params[:q].mb_chars.downcase}%")
    @taxons.delete_if { |taxon| @banner.taxons.include?(taxon) }

    respond_with(:admin, @banner, @taxons)
  end

  def remove_taxon
    @banner = Spree::Banner.find(params[:banner_id])
    @taxon = Spree::Taxon.find(params[:id])
    @banner.taxons.delete(@taxon)
    @banner.save
    @taxons = @banner.taxons

    respond_with(@taxon) { |format| format.js { render_js_for_destroy } }
  end

  def selected_taxons
    @taxons = Spree::Banner.find(params[:banner_id]).taxons

    respond_with(:admin, @taxons)
  end

  def select_taxon
    @banner = Spree::Banner.find(params[:banner_id])
    @taxon = Spree::Taxon.find(params[:id])
    @banner.taxons << @taxon
    @banner.save
    @taxons = @banner.taxons

    respond_with(:admin, @banner, @taxons)
  end
end

app/helpers/spree/banners_helper.rb
module Spree
  module BannersHelper

    def taxon_path(taxon)
      taxon.ancestors.reverse.collect { |ancestor| ancestor.name }.join( " >> ")
    end

    def insert_banner(params={})
      # class items show
      cl = params[:class] || "banner"

      # style items show
      style = params[:style] || "list"

      if params[:position].blank?
        if params[:max].blank?
          banner = Banner.enabled.shuffle
        else
          banner = Banner.enabled.shuffle.first(params[:max])
        end
      else
        if params[:max].blank?
          banner = Banner.by_position(Banner::POSITIONS[params[:position]]).shuffle
        else
          banner = Banner.by_position(Banner::POSITIONS[params[:position]]).shuffle.first(params[:max])
        end
      end

      unless banner.blank?
        if (style == "list")
          content_tag(:ul, raw(banner.map do |ban| content_tag(:li, link_to(image_tag(ban.attachment.url(image_size.to_sym)), ban.url), :class => cl) end.join) )
        else
          raw(banner.map do |ban|
            if ban.url?
              content_tag(style.to_sym, link_to(image_tag(ban.attachment.url(:custom)), ban.url), :class => cl)
            else
              content_tag(style.to_sym, image_tag(ban.attachment.url(:custom)), :class => cl)
            end
          end.join)
        end
      end
    end
  end
end

app/views/spree/admin/banners/_form.html.erb
<%= f.label :title, t("banner.title") %>
<%= f.text_field :title %>
<br />
<%= f.label :url, t("banner.url") %>
<%= f.text_field :url %>
<br />
<%= f.label :position, t("banner.position") %>
<%= f.select :position, options_for_select(Spree::Banner::POSITIONS.collect {|x| [x.first.capitalize, x.last]}, :selected => @banner.position) %>
<br />
<%= f.label :attachment_width, t("banner.attachment_width") %>
<%= f.text_field :attachment_width, :required => true %>
<br />
<%= f.label :attachment_height, t("banner.attachment_height") %>
<%= f.text_field :attachment_height %>
<br />
<%= f.label :enabled, t("banner.enabled") %>
<%= f.check_box :enabled %>
<br />
<%= f.label :attachment, t("banner.image") %>
<%= f.file_field :attachment %>
<br />
<%= f.object.attachment.blank? ? f.content_tag(:span, t("banner.no_image")) : image_tag(f.object.attachment.url(:thumbnail)) %>

<br />
<h1><%= t("taxons") %></h1>

<div id="selected-taxons" data-hook>
  <%= render :partial => 'selected', :locals => { :banner => f.object, :taxons => f.object.taxons } %>
</div>

app/views/spree/admin/banners/_selected.html.erb
<div id="selected-taxons" data-hook>
  <%= render :partial => 'taxon_table', :locals => { :taxons => taxons } %>
</div>

<%= form_tag '#' do %>
  <%= label_tag nil, t(:search) %>:
  <input id="searchtext" size="25">
<% end %>

<%= javascript_tag do %>
  function search_for_taxons(){
    $.ajax({
     data: {q: $("#searchtext").val() },
     dataType: 'html',
     success: function(request){
       jQuery('#search_hits').html(request);
     },
     type: 'POST',
     url: '<%= available_taxons_admin_banner_taxons_url(banner, :format => 'js') %>'
    });
  }

  $("#searchtext").keypress(function (e) {
    if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
      search_for_taxons();

      return false;
    } else {
       return true;
    }
  });

  $("#searchtext").delayedObserver(function() {
    search_for_taxons();
  }, 0.75);
<% end %>
<br />
<div id="search_hits" data-hook></div>

app/views/spree/admin/banners/_taxon_table.html.erb
<table class="index">
  <thead>
    <tr data-hook="taxons_header">
      <th><%= t(:name) %></th>
      <th><%= t(:path) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% taxons.each do |taxon| %>
      <tr id="<%= spree_dom_id(taxon) %>" data-hook="taxons_row">
        <td><%= taxon.name %></td>
        <td><%= taxon_path taxon %></td>
        <td class="actions">
          <%= link_to_delete taxon, :url => remove_taxon_admin_banner_taxon_url(@banner, taxon), :name => icon('delete') + ' ' + t(:remove) %>
        </td>
      </tr>
    <% end %>
    <% if taxons.empty? %>
      <tr data-hook="taxons_none"><td colspan="3"><%= t(:none) %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/banners/edit.html.erb
<h1><%= t("banner.editing_banner") %></h1>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @banner } %>

<%= form_for [:admin, @banner], :multipart => true do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/banners/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("banner.new_banner"), spree.new_admin_banner_path, :icon => 'add' %>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t("banner.listing") %></h1>

<table class="index sortable" data-hook data-sortable-link="<%= update_positions_admin_banners_url %>">
  <tr>
    <th><%= t("banner.title") %></th>
    <th><%= t("banner.url") %></th>
    <th><%= t("banner.position") %></th>
    <th><%= t("banner.enable") %></th>
    <th><%= t("banner.dimensions") %></th>
    <th><%= t(:action) %></th>
  </tr>
  <tbody>
    <% @banners.each do |banner| %>
      <tr class="<%= cycle('even', 'odd') %>" id="<%= dom_id banner %>">
        <td>
          <span class="handle"></span>
          <%= banner.title %>
        </td>
        <td><%= banner.url %></td>
        <td><%= Spree::Banner::POSITIONS.key(banner.position).to_s.capitalize %></td>
        <td><%= icon('tick') if banner.enabled %></td>
        <td><%= "#{banner.attachment_width} x #{banner.attachment_height}" %></td>
        <td>
          <%= link_to_edit banner %> &nbsp;
          <%= link_to_delete banner %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/banners/new.html.erb
<h1><%= t("banner.new_banner") %></h1>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @banner } %>

<%= form_for [:admin, @banner], :multipart => true do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
  <%= render :partial => 'spree/admin/shared/new_resource_links' %>
<% end %>

app/views/spree/admin/taxons/available_taxons.js.erb
<h4><%= t(:available_taxons) %></h4>
<table class="index">
  <thead>
    <tr>
      <th><%= t(:name) %></th>
      <th><%= t(:path) %></th>
      <th><%= t(:action) %></th>
    </tr>
  </thead>
  <tbody>
    <% @taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon, :sel) %>">
        <td><%= taxon.name %></td>
        <td><%= taxon_path taxon %></td>
        <td class="actions">
          <%= link_to icon(:add) + ' ' + t(:select),
                            select_taxon_admin_banner_taxon_path(@banner, taxon),
                           :remote => true, :class => 'iconlink' %>
        </td>
      </tr>
    <% end %>
    <% if @taxons.empty? %>
     <tr><td colspan="3"><%= t(:no_match_found) %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxons/select_taxon.js.erb
$("#selected-taxons").html("<%= escape_javascript(render(:partial => 'spree/admin/banners/taxon_table', :locals => { :banner => @banner, :taxons => @taxons })) %>");
$("#<%= dom_id @taxon, :sel %>").hide();